### ISSUE TITLE
only show changed attrs

### ISSUE THREAD

**Issue by cbarraford** [block42-blockchain-company/thornode-telegram-bot#34]
When sending out an alert, its only necessary to send the attributes that have changed, rather than all of them always

<img width="310" alt="Screen Shot 2020-05-02 at 1 25 18 PM" src="https://user-images.githubusercontent.com/246180/80871052-5fd54d00-8c78-11ea-90f6-fec9c28fd84b.png">

**Comment by mr-rooftop** [comment]
I feel like if we already send a message, the buttons below it take up so much space that it doesn't make a big diffference to send all attributes space wise. 

Additionally, I think it's informative to have a summary of the current values of monitored attributes.
Especially if you're out and about, suddenly receiving a notification that your slash points changed, you think 'fuck what could it be', then you see at the same time that your status is currently standby, and you already have an idea what the issue is.


If you @cbarraford want to have better readability of the changed value, I'd suggest we clearly state the changed value at the top of the notification message!

**Comment by rekt0x** [comment]
@mr-rooftop I think we should monitor all those values separately. So a check for each of those: status, bond, slash points, ...
And in case something changes, send a single message for the value that changed. If multiple values change, send multiple messages.

**Comment by cbarraford** [comment]
can we at least have a different text color for the changed values?
