### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by cbarraford** [block42-blockchain-company/thornode-telegram-bot#6]
Create a config file. It'll be pretty empty today, but we'll be adding more things to it.

**Comment by mr-rooftop** [comment]
What kind of configuration should be done in the config file?
Like whether or not to use the testing endpoint like we do now via the DEBUG flag?

**Comment by rekt0x** [comment]
I can imagine something like we now pass using enviroment variables `TELEGRAM_BOT_TOKE `, `DEBUG`, ... So instead of passing all those variables via ENV, we can just pass the path to the config file, e.g. `/home/block42/config.toml` to the docker and it reads the config from the file.

Is that what you thought about @cbarraford?

I'd suggest to go with a config using TOML format: https://github.com/toml-lang/toml

**Comment by cbarraford** [comment]
i was thinking addresses to full nodes (binance, bitcoin, eth), to monitor their health (ie adding blocks). The IP address to thorchain node (defaults to localhost).

**Comment by cbarraford** [comment]
toml is good

**Comment by rekt0x** [comment]
Binance, Bitcoin, Ethereum, etc. ... could also be localhost, right? but of course also on a different machine.
